### PR TITLE
Used a released camel version since SNAPSHOTS tend to "disappear" fro…

### PR DESCRIPTION
**Pull request by valdar**
…m repositories.

### CODE REVIEW

**Comment by nicolaferraro** [comment]
Tend to agree, wdyt @oscerd ?

**Comment by oscerd** [comment]
Sounds reasonable

**Comment by oscerd** [comment]
I'm 3.14 we could use local kamelets i guess, but we could live without it

**Comment by nicolaferraro** [comment]
> I'm 3.14 we could use local kamelets i guess, but we could live without it

The `--cp .` trick works also in 3.13

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Fine for me

**Review by nicolaferraro — APPROVED** [review]

**Pull request merged**
